services:
  - type: web
    name: sarpon-api
    env: php
    rootDir: pos-backend
    buildCommand: "composer install"
    startCommand: "php artisan serve --host 0.0.0.0 --port $PORT"
    plan: free
    envVars:
      # -- Konfigurasi Aplikasi Laravel --
      - key: APP_URL
        generateValue: true
      - key: APP_KEY
        value: base64:9vkgBZYtxg4VDiKxBmiLhNv8BiiW0uBV8IjCQysCKE4=

      # -- Koneksi ke Database Supabase --
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: db.rnohilsczuqdcsquhpmp.supabase.co
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: postgres
      - key: DB_USERNAME
        value: postgres
      - key: DB_PASSWORD
        value: Tribadrun3

      # -- Konfigurasi untuk Login (CORS) --
      - key: SANCTUM_STATEFUL_DOMAINS
        value: sarpon-react-laravel.vercel.app
      - key: SESSION_DOMAIN
        value: .vercel.app
